#!/bin/zsh -i
alias vi='nvim'
alias v="nvim"
alias reload='exec zsh'
alias bat="bat --pager='less -r'"
alias pg="ping -c 5 google.com | less"
alias mkd='mkdir -pv'
alias vimconfig='$EDITOR ~/.vimrc'
alias zshconfig='$EDITOR ~/.zshrc'
alias t='touch'
alias b='bat'
alias cpwd='pwd | pbcopy'
alias date="date '+%Y-%m-%d %H:%M'"
alias c='pbcopy'
alias p='pbpaste'
alias top='btop'
alias awsv='aws-vault'
