[manager]
prepend_keymap = [
    # palette keybindings
    { on = ["<Space>", "<Space>"], run = 'shell "qlmanage -p \"$@\"" --confirm', desc = "Quick look"},
    { on = ["<Space>", "d"], run = '''
        shell 'open -a Dropover "$@"' --confirm
    ''', desc = 'Drag and Drop' },
    { on = ["<Space>", "a"], run = '''
        shell 'airdrop "$1"' --confirm
    ''', desc = 'Send via Airdrop' },

    # quick jump
    { on = ["g", "c"], run = 'cd ~/.dotfiles', desc = 'Go to dotfiles' },
    { on = ["g", "d"], run = 'cd ~/downloads', desc = 'Go to downloads' },
    { on = ["g", "h"], run = 'cd ~', desc = 'Go to home directory' },
    { on = ["g", "D"], run = 'cd ~/desktop', desc = 'Go to desktop' },

    # shell commands
    { on = ":", run = 'shell --block --interactive'},

    # quick actions
    { on = "e", run = 'shell "nvim \"$@\"" --block --confirm'}
]
