[manager]
prepend_keymap = [
    { on = "<Space>", run = 'shell "qlmanage -p \"$@\"" --confirm'},
    { on = ":", run = 'shell --block --interactive'},
    { on = "e", run = 'shell "nvim \"$@\"" --block --confirm'},
    { on = [ "g", "d" ], run = '''
        shell 'open -a Dropover "$1"' --confirm
    ''', desc = 'Drag and Drop' },
    { on = [ "g", "a" ], run = '''
        shell 'airdrop "$1"' --confirm
    ''', desc = 'Send via Airdrop' },
    { on = [ "g", "c" ], run = 'cd ~/.dotfiles', desc = 'Go to dotfiles' }
]
