[manager]
sort_by = "btime"
sort_reverse = true
linemode = "btime"
sort_dir_first = false
show_symlink = true

[opener]
edit = [
    { run = 'nvim "$@"', block = true }
]
default = [
    { run = 'open "$@"', block = true }
]

[open]
prepend_rules = [
    { name = "*/", use = "default" },
    { name = "*.csv", use = "default"},
    { name = "*.pages", use = "default"}
]
