[manager]
sort_by = "btime"
sort_reverse = true
linemode = "btime"
sort_dir_first = false
show_symlink = true

[opener]
edit = [
    { run = 'nvim "$@"', block = true, desc = "Edit with Neovim" },
    { run = 'code "$@"', block = true, desc = "Edit with vscode" }
]
open = [
    { run = 'open "$@"', block = true, desc = "Open with default application" }
]
reveal = [
    { run = 'open -R "$@"', block = true, desc = "Reveal in Finder" }
]
run_bash = [
    { run = 'bash "$@"', block = true, desc = "Run in Bash Shell" }
]
run_fish = [
    { run = 'fish "$@"', block = true, desc = "Run in Fish Shell" }
]
default = [
    { run = 'open "$@"', block = true, desc = "Open with default application" },
    { run = 'ouch compress "$@" "$1.zip"', block = true, desc = "Compress File/s"},
    { run = 'open -R "$@"', block = true, desc = "Reveal in Finder" }
]

[open]
prepend_rules = [
    { mime = "*", use = "default" },
    { name = "*.fish", use = ["run_fish", "edit", "default"]},
]

[plugin]
prepend_preloaders = [ ]
prepend_previewers = [
    { name = "*.key", run = "noop" },
    { name = "*.pages", run = "noop" },
    { name = "*.numbers", run = "noop" },
]
