require("plugins.ui")
require("plugins.oil")
require("plugins.telescope")
require("plugins.theme")
require("plugins.completion")
require("plugins.treesitter")
require("plugins.git")
require("plugins.snacks")
-- require("plugins.formatter")
-- require("plugins.dap")
-- require("plugins.linting")
