alias vi='nvim'
alias v="nvim"
alias reload='. ~/.config/fish/config.fish'
alias bat="bat --pager='less -r'"
alias pg="ping -c 5 google.com | less"
alias vimconfig='$EDITOR ~/.vimrc'
alias t='touch'
alias b='bat'
alias cpwd='pwd | pbcopy'
alias date="date '+%Y-%m-%d %H:%M'"
alias c='pbcopy'
alias p='pbpaste'
alias top='btop'
alias awsv='aws-vault'
alias cl='clear'
alias e='$EDITOR'
alias ls='eza -s type --icons'
alias ll='eza -s type --icons -la --total-size'
alias dl='curl --output-dir ~/Downloads -O'
alias delta='delta --line-numbers --side-by-side'
alias speedtest='speedtest --bytes | less'
alias imgcat='wezterm imgcat'
alias fm='xplr'
alias lazygit='lazygit -ucf ~/.config/lazygit/config.yml'
